FORMAT: 1A
HOST: https://fast-food--app-v2.herokuapp.com/api/v2

# fast-food-api v2
This is an online ordering app

# Group auth

## Auth Login [/auth/login]

### Login [POST]
This endpoint signs in a user with email and password

+ Request (application/json)
    + Attributes (LoginRequest)

    + Body

            {
                "email": "new@gmail.com",
                "password": "aA2345678"
            }


+ Response 200 




## Auth Signup [/auth/signup]

### Register [POST]
This endpoint signsup a user with username, email and password

+ Request (application/json)
    + Attributes (RegisterRequest)

    + Body

            {
                "username": "admin",
                "email": "admin@gmail.com",
                "password": "bB123456",
                "confirm password": "bB123456"
            }


+ Response 200 





# Group menu

## Menu [/menu]

### Add a meal  admin [POST]
This is an admin endpoint for adding food items

+ Request (application/json)
    + Headers

            x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNTM4Njk1NzE3fQ.AFEs-RFPXMW4JSFFML6-1FuQa6I-xH0AWFtcEIP7SwY

    + Attributes (Add a meal  adminRequest)

    + Body

            {
                "item": "fries",
                "price": 250,
                "description": "with source"
            }


+ Response 200 



### Get all meals [GET]
This is a public endpoint for viewing items in the menu

+ Request (application/json)
    + Headers

            x-access-token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTM4Njk1NTk3fQ.l1lDlHNOOStQE5QGehwFgpZdfI3w2TjkuWYUfaxuEaY




+ Response 200 





# Group adminorders

## Orders [/orders]

### Get all orders [GET]
Get all user orders -accessed by admins only

+ Request 
    + Headers

            x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNTM4Njk1NzE3fQ.AFEs-RFPXMW4JSFFML6-1FuQa6I-xH0AWFtcEIP7SwY




+ Response 200 




## Orders  [/orders/<orderId>]

### Update order status [PUT]
This endpoint updates status by id and is only accessed by admins

+ Request (application/json)
    + Headers

            x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTM4NjYxODkzfQ.JTd-Fas34gNzas5-in6eBtYe61hEUoNG_PT_k9o4Yqs

    + Attributes (Update order statusRequest)

    + Body

            {
                "status": "completed"
            }


+ Response 200 



### Get order by id [GET]
This endpoint gets an order by id and is only accessed by admins

+ Request (application/json)
    + Headers

            x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNTM4Njk1NzE3fQ.AFEs-RFPXMW4JSFFML6-1FuQa6I-xH0AWFtcEIP7SwY




+ Response 200 





# Group users

## Users Orders [/users/orders]

### Get user history [GET]
Logged in users can get a list of ordered food items

+ Request (application/json)
    + Headers

            x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNTM4Njk1NzE3fQ.AFEs-RFPXMW4JSFFML6-1FuQa6I-xH0AWFtcEIP7SwY




+ Response 200 



### Post an order [POST]
Logged in users can order food items

+ Request (application/json)
    + Headers

            x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNTM4Njc1MjUwfQ.ol7owgzEqkC1GCiPbSqT8WEJ-8rcqAgdD93vjRg8nZ8

    + Attributes (Post an orderRequest)

    + Body

            {
                "mealId": "2",
                "quantity": 5,
                "address": "K-Road"
            }


+ Response 200 





# Group promote

## Promote  [/promote/<orderId>]

### Promote user [POST]
Admin users can promote other users to be admin or client

+ Request (application/json)
    + Headers

            x-access-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZXhwIjoxNTM4Njk1NzE3fQ.AFEs-RFPXMW4JSFFML6-1FuQa6I-xH0AWFtcEIP7SwY

    + Attributes (Promote userRequest)

    + Body

            {
                "type": "client"
            }


+ Response 200 





# Group Users

## Users [/users]

### Users [POST]
Get all users

+ Request (application/json)
    + Headers

            x-access-token:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTM4Njk1MzY4fQ.FqskDjRZOdu02r0hYFqzeKpdc1BsNCJLPnjrTqvd6dw

    + Attributes (UsersRequest)

    + Body

            {
                "type": "admin"
            }


+ Response 200 





# Data Structures

## LoginRequest (object)


### Properties
+ `email`: `new@gmail.com` (string, required) 
+ `password`: `aA2345678` (string, required) 


## RegisterRequest (object)


### Properties
+ `username`: `admin` (string, required) 
+ `email`: `admin@gmail.com` (string, required) 
+ `password`: `bB123456` (string, required) 
+ `confirm password`: `bB123456` (string, required) 


## Add a meal  adminRequest (object)


### Properties
+ `item`: `fries` (string, required) 
+ `price`: `250` (number, required) 
+ `description`: `with source` (string, required) 


## Update order statusRequest (object)


### Properties
+ `status`: `completed` (string, required) 


## Post an orderRequest (object)


### Properties
+ `mealId`: `2` (string, required) 
+ `quantity`: `5` (number, required) 
+ `address`: `K-Road` (string, required) 


## Promote userRequest (object)


### Properties
+ `type`: `client` (string, required) 


## UsersRequest (object)


### Properties
+ `type`: `admin` (string, required)
